import type { Trip } from '../types/trip'

export function buildDemoTrip(): Trip {
  const now = new Date().toISOString()

  return {
    id: 'demo-trip-th-jp-kr',
    name: 'Thailand → Japan → Korea',
    totalBudget: 3000,
    currency: 'EUR',
    createdAt: now,
    updatedAt: now,
    originCity: 'Munich',
    originCountry: 'Germany',
    originLat: 48.1351,
    originLng: 11.582,
    transitToFirst: {
      id: 'demo-t0',
      type: 'Flight',
      fromCity: 'Munich',
      toCity: 'Bangkok',
      departureDate: '2026-09-01',
      arrivalDate: '2026-09-01',
      cost: 420,
      airline: 'Lufthansa',
      flightNumber: 'LH772',
      durationMinutes: 690,
    },
    segments: [
      {
        id: 'demo-s1',
        city: 'Bangkok',
        country: 'Thailand',
        arrivalDate: '2026-09-01',
        departureDate: '2026-09-07',
        lat: 13.7563,
        lng: 100.5018,
        accommodation: {
          id: 'demo-a1',
          name: 'Lub d Bangkok Silom',
          type: 'Hostel',
          costPerNight: 18,
        },
        activities: [
          { id: 'demo-act1', name: 'Grand Palace & Wat Phra Kaew', cost: 15, date: '2026-09-02' },
          { id: 'demo-act2', name: 'Chatuchak Weekend Market', cost: 20, date: '2026-09-03' },
          { id: 'demo-act3', name: 'Muay Thai boxing show', cost: 30, date: '2026-09-04' },
          { id: 'demo-act4', name: 'Chao Phraya dinner cruise', cost: 35, date: '2026-09-05' },
        ],
        transitToNext: {
          id: 'demo-t1',
          type: 'Flight',
          fromCity: 'Bangkok',
          toCity: 'Chiang Mai',
          departureDate: '2026-09-07',
          arrivalDate: '2026-09-07',
          cost: 45,
          airline: 'AirAsia',
          flightNumber: 'FD3162',
          durationMinutes: 65,
        },
      },
      {
        id: 'demo-s2',
        city: 'Chiang Mai',
        country: 'Thailand',
        arrivalDate: '2026-09-07',
        departureDate: '2026-09-11',
        lat: 18.7883,
        lng: 98.9853,
        accommodation: {
          id: 'demo-a2',
          name: 'Zleep Hostel Nimman',
          type: 'Hostel',
          costPerNight: 14,
        },
        activities: [
          { id: 'demo-act5', name: 'Doi Suthep Temple', cost: 5, date: '2026-09-08' },
          { id: 'demo-act6', name: 'Elephant Nature Park', cost: 65, date: '2026-09-09' },
          { id: 'demo-act7', name: 'Night Bazaar & street food', cost: 25, date: '2026-09-10' },
        ],
        transitToNext: {
          id: 'demo-t2',
          type: 'Flight',
          fromCity: 'Chiang Mai',
          toCity: 'Tokyo',
          departureDate: '2026-09-11',
          arrivalDate: '2026-09-11',
          cost: 290,
          airline: 'Thai Airways',
          flightNumber: 'TG682',
          durationMinutes: 360,
        },
      },
      {
        id: 'demo-s3',
        city: 'Tokyo',
        country: 'Japan',
        arrivalDate: '2026-09-11',
        departureDate: '2026-09-17',
        lat: 35.6762,
        lng: 139.6503,
        accommodation: {
          id: 'demo-a3',
          name: 'Khaosan Tokyo Ninja',
          type: 'Hostel',
          costPerNight: 38,
        },
        activities: [
          { id: 'demo-act8', name: 'teamLab Borderless', cost: 30, date: '2026-09-12' },
          { id: 'demo-act9', name: 'Shinjuku Gyoen garden', cost: 5, date: '2026-09-13' },
          { id: 'demo-act10', name: 'Day trip to Nikkō', cost: 40, date: '2026-09-14' },
          { id: 'demo-act11', name: 'Shibuya crossing & ramen crawl', cost: 20, date: '2026-09-15' },
        ],
        transitToNext: {
          id: 'demo-t3',
          type: 'Flight',
          fromCity: 'Tokyo',
          toCity: 'Seoul',
          departureDate: '2026-09-17',
          arrivalDate: '2026-09-17',
          cost: 95,
          airline: 'Jeju Air',
          flightNumber: '7C1102',
          durationMinutes: 150,
        },
      },
      {
        id: 'demo-s4',
        city: 'Seoul',
        country: 'South Korea',
        arrivalDate: '2026-09-17',
        departureDate: '2026-09-21',
        lat: 37.5665,
        lng: 126.978,
        accommodation: {
          id: 'demo-a4',
          name: 'Kimchee Guesthouse Hongdae',
          type: 'Guesthouse',
          costPerNight: 28,
        },
        activities: [
          { id: 'demo-act12', name: 'Gyeongbokgung Palace', cost: 3, date: '2026-09-18' },
          { id: 'demo-act13', name: 'DMZ tour', cost: 50, date: '2026-09-19' },
          { id: 'demo-act14', name: 'Korean BBQ dinner', cost: 30, date: '2026-09-20' },
          { id: 'demo-act15', name: 'N Seoul Tower', cost: 12, date: '2026-09-20' },
        ],
      },
    ],
    transitFromLast: {
      id: 'demo-t4',
      type: 'Flight',
      fromCity: 'Seoul',
      toCity: 'Munich',
      departureDate: '2026-09-21',
      arrivalDate: '2026-09-21',
      cost: 380,
      airline: 'Korean Air',
      flightNumber: 'KE905',
      durationMinutes: 720,
    },
  }
}
